using API.Models;
using Microsoft.EntityFrameworkCore;


namespace API.Context
{
    public class AppDbContext : DbContext
    {

        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<Destino> Destino { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Destino>().HasData(
                new Destino { Id = 1, Cidade = "Porto Seguro", Detalhes = "Porto Seguro é uma cidade no sul da Bahia com praias paradisíacas, centro histórico preservado e cultura indígena. Além de sua beleza natural, oferece passeios de escuna, trilhas ecológicas e animada vida noturna.", Estado = "Bahia", Img = "https://resortnabahia.com.br/wp-content/uploads/2019/01/lateral-resort-mar.jpg", Pais = "Brasil" },
                new Destino { Id = 2, Cidade = "Rio de Janeiro", Detalhes = "O Rio de Janeiro é uma cidade vibrante e encantadora, famosa por suas praias, Carnaval e Cristo Redentor. Com sua rica história e cultura, é um destino bastante popular que oferece muitas opções de lazer.", Estado = "Rio de Janeiro", Img = "https://www.melhoresdestinos.com.br/wp-content/uploads/2019/08/rio-de-janeiro-capa2019-01.jpg", Pais = "Brasil" },
                new Destino { Id = 3, Cidade = "Salvador", Detalhes = "Salvador é uma cidade histórica da Bahia, conhecida por sua rica cultura afro-brasileira, culinária e festas populares. Com belas praias e monumentos históricos, é um destino popular para quem busca história e cultura.", Estado = "Bahia", Img = "https://a.cdn-hotels.com/gdcs/production67/d1025/9c42e257-fce5-4600-97d1-c3f3c6afd86b.jpg", Pais = "Brasil" },
                new Destino { Id = 4, Cidade = "João Pessoa", Detalhes = "João Pessoa é uma cidade acolhedora, com praias de águas cristalinas e paisagens encantadoras. O centro histórico é repleto de construções barrocas e os passeios de catamarã pelo rio Paraíba são imperdíveis.", Estado = "Paraíba", Img = "https://s2.static.brasilescola.uol.com.br/be/2023/08/1-joao-pessoa.jpg", Pais = "Brasil" },
                new Destino { Id = 5, Cidade = "Porto de Galinhas", Detalhes = "Porto de Galinhas é uma cidade no estado de Pernambuco, conhecida por suas praias de águas cristalinas e piscinas naturais formadas por corais. Com clima tropical, é um destino popular para quem busca diversão.", Estado = "Pernambuco", Img = "https://thumbcdn-z.hotelurbano.net/6GQUgE4O8rtSqaQOWE2PWT7ZiUY=/444x270/center/middle/filters:quality(40)/https://s3.amazonaws.com/legado-prod/prod/ofertas/imagens/2023/07/26/12/44/iStock_1128300455.jpg", Pais = "Brasil" },
                new Destino { Id = 6, Cidade = "Caldas Novas ", Detalhes = "Caldas Novas é uma cidade termal em Goiás, famosa pelas águas quentes e pelas piscinas naturais. Além dos banhos relaxantes, é possível aproveitar a culinária local, passeios de barco e visitar o Lago Corumbá.", Estado = "Goiás", Img = "https://thumbcdn-z.hotelurbano.net/Wlq3zqRosR7oz5rQQeIpPr2j52A=/444x270/center/middle/filters:quality(40)/https://s3.amazonaws.com/legado-prod/prod/ofertas/imagens/2023/10/31/13/21/10_shutterstock_1315449212.jpg", Pais = "Brasil" },
                new Destino { Id = 7, Cidade = "Natal", Detalhes = "Natal é uma cidade encantadora do Nordeste brasileiro, conhecida por suas praias paradisíacas, dunas de areia e falésias coloridas. Com clima agradável, é um destino popular para quem busca sol, mar e tranquilidade.", Estado = "Rio Grande do Norte", Img = "https://thumbcdn-z.hotelurbano.net/DW3PZYnFMw9iVyekQJRTaTTF3C4=/444x270/center/middle/filters:quality(40)/https://s3.amazonaws.com/legado-prod/prod/ofertas/imagens/2023/11/08/15/09/Praia_de_Ponta_Negra.png", Pais = "Brasil" },
                new Destino { Id = 8, Cidade = "Fortaleza", Detalhes = "Jericoacoara é um verdadeiro paraíso brasileiro, com praias de areia branca, dunas, lagoas cristalinas e noites estreladas. Um lugar para quem busca contato com a natureza, com atividades como caminhadas e passeios de buggy.", Estado = "Ceará", Img = "https://thumbcdn-z.hotelurbano.net/D-t0oayNyr8YzFSmtsruGJXhVfs=/444x270/center/middle/filters:quality(40)/https://s3.amazonaws.com/legado-prod/prod/ofertas/imagens/2023/08/14/17/49/iStock_536474512.jpg", Pais = "Brasil" },
                new Destino { Id = 9, Cidade = "Cabo Frio", Detalhes = "Cabo Frio é um destino popular na região dos Lagos no Brasil, famosa por suas belas praias de águas cristalinas e areias brancas. A cidade oferece várias opções de lazer, como esportes aquáticos, passeios de barco e mergulho.", Estado = "Rio de Janeiro", Img = "https://thumbcdn-z.hotelurbano.net/H44iQZJarYpMvwMbDfOEboBZz_Q=/444x270/center/middle/filters:quality(40)/https://s3.amazonaws.com/legado-prod/prod/ofertas/imagens/2023/08/28/17/28/shutterstock_1265227072_Cabo_Frio.jpg", Pais = "Brasil" },
                new Destino { Id = 10, Cidade = "Bauneário Camboriú", Detalhes = "Balneário Camboriú é uma cidade turística no litoral de Santa Catarina, conhecida por suas belas praias e vida noturna agitada. Com arranha-céus e modernas construções, a cidade oferece uma atmosfera sofisticada.", Estado = "Santa Catarina", Img = "https://thumbcdn-z.hotelurbano.net/nqJY6vKWHlh6f5w1M0edad-fp-4=/444x270/center/middle/filters:quality(40)/https://s3.amazonaws.com/legado-prod/prod/ofertas/imagens/2023/10/27/22/52/Capturar.JPG", Pais = "Brasil" },
                new Destino { Id = 11, Cidade = "Lisboa", Detalhes = "Lisboa é a capital de Portugal e uma das cidades mais charmosas da Europa. Com diversos pontos turísticos, como a Torre de Belém e o Mosteiro dos Jerónimos, é um destino popular para quem busca história e cultura.", Estado = "Lisboa", Img = "https://media.istockphoto.com/id/1221460597/pt/foto/yellow-vintage-tram-on-the-street-in-lisbon-portugal.jpg?s=612x612&w=0&k=20&c=ZbKrrfXuPumtrc0nnU74D9aa9fed7ZuXM1CTrcV7Qq8=", Pais = "Portugal" },
                new Destino { Id = 12, Cidade = "Orlando", Detalhes = "Orlando é uma cidade localizada na Flórida, nos Estados Unidos, conhecida por ser a capital mundial dos parques temáticos. Com atrações como Walt Disney World, é um destino popular para quem busca diversão em família.", Estado = "Flórida", Img = "https://documentodeviagem.com/dicas-da-disney-e-orlando/disney-magic-kingdom-documento-de-viagem-1024x768_edited/", Pais = "Estado Unidos" },
                new Destino { Id = 13, Cidade = "Cancún", Detalhes = "Cancún é uma cidade localizada na península de Yucatán, no México, conhecida por suas praias de água cristalina e areia branca. Com clima tropical e ambiente festivo, é um destino popular para quem busca diversão.", Estado = "Quintano Roo,", Img = "https://www.remessaonline.com.br/blog/wp-content/uploads/2022/05/viagem-para-cancun-1170x780.jpg.optimal.jpg", Pais = "México" },
                new Destino { Id = 14, Cidade = "Punta Cana", Detalhes = "Punta Cana é uma cidade localizada na República Dominicana, conhecida por suas praias de areia branca e águas cristalinas. Com clima tropical e ambiente relaxante, é um destino popular para quem busca tranquilidade.", Estado = "La Altagracia", Img = "https://imgmd.net/images/v1/guia/1700155/punta-cana.jpg", Pais = "República Dominicana" },
                new Destino { Id = 15, Cidade = "Santiago", Detalhes = "Santiago é a capital do Chile, uma cidade vibrante e moderna com uma rica herança cultural e histórica. Com diversas atrações turísticas, como a Plaza de Armas, é um destino popular para quem busca arte e história.", Estado = "Santiago", Img = "https://i3.visitchile.com/img/GalleryContent/615/COSTANERA_CENTER.jpg", Pais = "Chile" },
                new Destino { Id = 16, Cidade = "Paris", Detalhes = "Paris é uma cidade icônica na França, conhecida por sua arquitetura clássica, museus renomados e gastronomia sofisticada. Com uma atmosfera charmosa e romântica, é um destino popular para quem busca cultura e história.", Estado = "Île-de-France", Img = "https://www.viajaquepassa.com.br/wp-content/uploads/2021/02/torre-eiffel-paris.png", Pais = "França" },
                new Destino { Id = 17, Cidade = "Tóquio", Detalhes = "Tóquio é uma cidade vibrante e frenética, onde a tradição e a modernidade se misturam. É um paraíso para os amantes de tecnologia, moda, gastronomia e cultura pop, com uma infinidade de experiências para todos os gostos.", Estado = "Ilha de Honsu.", Img = "https://static.mundoeducacao.uol.com.br/mundoeducacao/conteudo/toquio-pontos-turisticos.jpg", Pais = "Japão" },
                new Destino { Id = 18, Cidade = "Cartagena", Detalhes = "Descubra as praias paradisíacas, a rica história, a gastronomia deliciosa e a cultura encantadora de Cartagena. Explore suas ruas movimentadas, mar azul cristalino e desfrute de festas e festivais animados, incluindo o famoso Carnaval. Uma mistura mágica de história e modernidade, este destino caribenho é o lugar perfeito para uma aventura inesquecível.", Estado = "Bolívar", Img = "https://media.tacdn.com/media/attractions-splice-spp-674x446/0e/54/b4/96.jpg", Pais = "Colômbia" },
                new Destino { Id = 19, Cidade = "Florença", Detalhes = "A deslumbrante cidade italiana situada na região da Toscana, é um tesouro artístico e cultural que encanta visitantes há séculos. Lar de algumas das obras-primas mais icônicas da Renascença, como o David de Michelangelo e a cúpula da Catedral de Santa Maria del Fiore projetada por Brunelleschi, Florença é um museu a céu aberto. Suas ruas estreitas e pitorescas, pontes românticas sobre o rio Arno e praças charmosas, como a Piazza della Signoria, convidam os visitantes a explorar cada canto da cidade. Além de sua riqueza artística, Florença também é famosa por sua culinária deliciosa, destacando pratos como a pasta fresca, a carne de porco assada e o famoso gelato italiano.", Estado = "Toscana", Img = "https://www.passagenspromo.com.br/blog/wp-content/uploads/2022/01/Florenca-Italia-740x415.jpg", Pais = "Itália" },
                new Destino { Id = 20, Cidade = "Las Vegas", Detalhes = "Descubra a cidade mais famosa dos cassinos e entretenimento! Las Vegas oferece festas animadas, gastronomia de classe mundial, shows espetaculares e luxuosos resorts. Explore a cidade que nunca dorme!", Estado = "Nevada", Img = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/34/2d/28/caption.jpg?w=700&h=-1&s=1&cx=662&cy=604&chk=v1_8984ddf3493edfb8c896", Pais = "Estados Unidos" }
                );
        }
    }
}
